# database
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/security_db
    username: gyeom
    password: 3677

  # Spring data jpa
  jpa:
    open-in-view: true
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

  #Spring Security
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 260314451567-79g6jdos2ea28t1k6fau2d4u7amu4110.apps.googleusercontent.com
            client-secret: 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
            scope: profile, email
            redirect-uri: http://localhost:8080/login/oauth2/code/google
          facebook:
            client-id: 850791733338400
            client-secret: 7b3572092faba8e7a39917d4129612cf
            scope: public_profile, email
          naver:
            client-id: 7DloIgUmPVn5KMlCO_Yd
            client-secret: Huryy9bYAe
            scope: name, email
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/naver

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize  # 네이버 로그인 인증 요청
            token-uri: https://nid.naver.com/oauth2.0/token  # 접근 토큰 요청
            user-info-uri: https://openapi.naver.com/v1/nid/me # 프로필 정보 요청
            user-name-attribute: response # 회원정보를 json으로 받는데 response라는 key 값으로 네이버가 리턴해줌

  data:
    redis:
      port: 6379
      host: localhost

secret:
  key: qwewrlnmzlnmxzcvlxcvjsdpisfdapsf9823038384jsjsdfjdsfjkdxmmz